### ISSUE TITLE
Ability to add a geoJSON multiline or GeoJSON as a Place to use in a StoryMap chapter

### ISSUE THREAD

**Issue by martenwilmink** [martenwilmink/reframe-brain#11]
## Issue description [(i)](## "A (short) description as to what the issue is.")

Current implementation allows to add a singular location (i.e. a 'pin') as a Place to be used in a StoryMap chapter. We'd like to also use geoJSON objects to allow multiLine and polygon location objects to be used as Places.

## New specification [(i)](## "A clear and unambiguous extended specification of the new or updated functionality. References to external documents should be temporary and replaced with contents before the ticket is taken up by a developer.")

- Parse and render geoJSON object inputs for a Place entity when selected in a StoryMap chapter

## New design [(i)](## "A clear and unambiguous extended design of the new functionality. References to external documents should be temporary and replaced with contents before the ticket is taken up by a developer.")
- N/A (see existing design)

## Existing specification [(i)](## "Link(s) to the specification regarding the relevant existing functionality. The links or surrounding text should clearly indicate what is being referenced, so the information can also be found if the link goes 404.")
- N/A

## Existing design [(i)](## "If the issue concerns visual matters at all, link(s) to the designs regarding the relevant existing functionality. The links or surrounding text should clearly indicate what is being referenced, so the information can also be found if the link goes 404.")

<img width="779" alt="rb-11-geoJSON-place" src="https://github.com/user-attachments/assets/1751a124-76f7-4840-bd0c-d7efcae2f925">

## Additional information [(i)](## "Suggestions for technical implementation, solution pointers, information that provides extra context or background information, related issues, comments, etc.")
- We should also create a separate issue for KML support
- For a next iteration, especially when we decide to let other users add Places, the UX for the modal window Edit Place should be considered, since it seems we can add Lat/Long + Address + GeoJSON + KML all at the same time. Probably only allow one at a time or indicate clearly which input takes precedence. 

## TODO  [(i)](## "Checklist to ensure critical reviews of specification are done by issue creator and lead developer before actual development starts.")
- [x] Self review of issue specification
- [x] Lead dev review of issue specification

**Comment by hugopeek** [comment]
@martenwilmink Good point that it is not immediately clear which data takes precedence, when adding a Place to a StoryMap chapter.

For now: GeoJSON is used if present, otherwise a regular marker is shown.
