### ISSUE TITLE
Ability to add a multilayer StoryMap on a page of Story content type

### ISSUE THREAD

**Issue by martenwilmink** [martenwilmink/reframe-brain#13]
## Issue description [(i)](## "A (short) description as to what the issue is.")

Currently we have a **ReframeStoryMap** template for a Resource that allows adding StoryMap Chapters to create a StoryMap with scrolling content. We would like to be able to add a 'regular' Multiple Layer Map Content Block on the same page as well, to give users the ability to add  supporting/contextual map layers and locations. It seems a user 

## New specification [(i)](## "A clear and unambiguous extended specification of the new or updated functionality. References to external documents should be temporary and replaced with contents before the ticket is taken up by a developer.")

- Ability to add Map (Multiple Layers) Content Block to resource with ReframeStoryMap template and ensure contents of the Multilayer Map are rendered in the same map as the StoryMap chapter geodata. 
- If possible, retain the functionality where locations on the multilayer map can be clicked.

## New design [(i)](## "A clear and unambiguous extended design of the new functionality. References to external documents should be temporary and replaced with contents before the ticket is taken up by a developer.")
- See existing design

## Existing specification [(i)](## "Link(s) to the specification regarding the relevant existing functionality. The links or surrounding text should clearly indicate what is being referenced, so the information can also be found if the link goes 404.")

- User is able to add a new Single Column layout and add a new Map (Multiple Layers) content block

## Existing design [(i)](## "If the issue concerns visual matters at all, link(s) to the designs regarding the relevant existing functionality. The links or surrounding text should clearly indicate what is being referenced, so the information can also be found if the link goes 404.")

<img width="928" alt="rb-13-exisiting-Map-Multiple-Layers-CB" src="https://github.com/user-attachments/assets/1908329e-391a-41bd-90af-5a42e2cba89c">

## Additional information [(i)](## "Suggestions for technical implementation, solution pointers, information that provides extra context or background information, related issues, comments, etc.")
- It seems we don't need to add extra functionality in the manager / CB's, but only make sure the current implementation shows both the StoryMap chapter locations and the Multilayer Map locations in the same map

## TODO  [(i)](## "Checklist to ensure critical reviews of specification are done by issue creator and lead developer before actual development starts.")
- [x] Self review of issue specification
- [x] Lead dev review of issue specification

**Comment by hugopeek** [comment]
@martenwilmink Yes, same content block can be used for this. Only difference is that it needs to be placed inside a StoryMap Layers layout:

![image](https://github.com/user-attachments/assets/d7286f26-5b13-4b1f-826e-7ca9b35e64ab)
