### ISSUE TITLE
Ability for users to scroll from chapter to chapter in order, with the map flying to the marker

### ISSUE THREAD

**Issue by martenwilmink** [martenwilmink/reframe-brain#3]
## Issue description [(i)](## "A (short) description as to what the issue is.")

Ability for users to scroll the sidebar with StoryMap Chapter content and jump to the corresponding location on the map.

## New specification [(i)](## "A clear and unambiguous extended specification of the new or updated functionality. References to external documents should be temporary and replaced with contents before the ticket is taken up by a developer.")

- User scrolls sidebar and jumps to corresponding marker on the map when StoryMap Chapter container hits the top of the browser window

## New design [(i)](## "A clear and unambiguous extended design of the new functionality. References to external documents should be temporary and replaced with contents before the ticket is taken up by a developer.")

<img width="1210" alt="rb-15-exisiting-StoryMapChapter" src="https://github.com/user-attachments/assets/bcbc8267-a9a6-463a-a677-c7059dd72496">

## Existing specification [(i)](## "Link(s) to the specification regarding the relevant existing functionality. The links or surrounding text should clearly indicate what is being referenced, so the information can also be found if the link goes 404.")
- N/A

## Existing design [(i)](## "If the issue concerns visual matters at all, link(s) to the designs regarding the relevant existing functionality. The links or surrounding text should clearly indicate what is being referenced, so the information can also be found if the link goes 404.")

- N/A

## Additional information
- Ensure behaviour works properly on mobile devices
- Related: #4

**Comment by hugopeek** [comment]
Still work in progress, but included in v0.2.0. This approach uses the [Visibilty behaviour from Fomantic UI](https://fomantic-ui.com/behaviors/visibility.html#/settings).

**Comment by martenwilmink** [comment]
@hugopeek I've updated the spec, but please check to verify or update where needed for the intended behaviour. I'll leave this assigned to you, when it's done in your opinion you can assign it back to me for Functional review.

**Comment by martenwilmink** [comment]
@hugopeek are you still working on this part? Otherwise this issue can be set to Completed, since the functionality seems to work.

**Comment by hugopeek** [comment]
@martenwilmink Yes, good to go. Mobile functionality might not be optimal yet, but it's acceptable to me (with the content area minimizing to the left, when map has focus).
