### ISSUE TITLE
 Ability for users to click markers and load chapter content

### ISSUE THREAD

**Issue by martenwilmink** [martenwilmink/reframe-brain#4]
## Issue description [(i)](## "A (short) description as to what the issue is.")

Currently only scrolling the sidebar content will trigger jumping the markers. Users should be able to click a marker and scroll to the corresponding content.

## New specification [(i)](## "A clear and unambiguous extended specification of the new or updated functionality. References to external documents should be temporary and replaced with contents before the ticket is taken up by a developer.")

- When user clicks a StoryMap marker, then browser should jumpScroll to the corresponding StoryMap Chapter content in the sidebar

## New design [(i)](## "A clear and unambiguous extended design of the new functionality. References to external documents should be temporary and replaced with contents before the ticket is taken up by a developer.")
- N/A

## Existing specification [(i)](## "Link(s) to the specification regarding the relevant existing functionality. The links or surrounding text should clearly indicate what is being referenced, so the information can also be found if the link goes 404.")
- When user scrolls the sidebar with StoryMap Chapter content, then the map in the browser jumps to the corresponding location

## Existing design [(i)](## "If the issue concerns visual matters at all, link(s) to the designs regarding the relevant existing functionality. The links or surrounding text should clearly indicate what is being referenced, so the information can also be found if the link goes 404.")

<img width="1210" alt="rb-15-exisiting-StoryMapChapter" src="https://github.com/user-attachments/assets/35fb208d-df41-4997-abd1-37a978bae70a">

## Additional information
- Maybe we can think of other navigation aides (like 'Next/Previous' buttons or something to implement in a separate issue

**Comment by hugopeek** [comment]
@martenwilmink I'm happy with how the basic navigation works now. Indeed, prev/next buttons would be nice to have still, as well as a button to zoom out to starting position. Let's make new issues for those.
