### ISSUE TITLE
Ability to order Chapters via drag and drop in StoryBook with ContentBlocks

### ISSUE THREAD

**Issue by martenwilmink** [martenwilmink/reframe-brain#5]
## Issue description [(i)](## "A (short) description as to what the issue is.")
...

## New specification [(i)](## "A clear and unambiguous extended specification of the new or updated functionality. References to external documents should be temporary and replaced with contents before the ticket is taken up by a developer.")
...

## New design [(i)](## "A clear and unambiguous extended design of the new functionality. References to external documents should be temporary and replaced with contents before the ticket is taken up by a developer.")
...

## Existing specification [(i)](## "Link(s) to the specification regarding the relevant existing functionality. The links or surrounding text should clearly indicate what is being referenced, so the information can also be found if the link goes 404.")
- ...

## Existing design [(i)](## "If the issue concerns visual matters at all, link(s) to the designs regarding the relevant existing functionality. The links or surrounding text should clearly indicate what is being referenced, so the information can also be found if the link goes 404.")
- ...

## Additional information
...

**Comment by hugopeek** [comment]
Chapters in StoryMap can be added and sorted as ContentBlocks layouts.

Please note that the actual ContentBlocks elements are not included in this repository, but part of the project database.
