### ISSUE TITLE
StoryBook functionality

### ISSUE THREAD

**Issue by martenwilmink** [martenwilmink/reframe-brain#6]
## Issue description [(i)](## "A (short) description as to what the issue is.")

Ability for users to create StoryBooks in MODx via ContentBlocks. A StoryBook can be added as a layer to a StoryMap. A StoryBook can contain one or more Chapters, that are represented on a map with (custom) markers. A chapter is a content type in modx that is built with ContentBlocks. For each chapter we can determine the presentation. The chapters are shown in order and can be navigated by the user either scrolling through the content (i.e. from chapter to chapter), using next / previous buttons or dots navigation), or by clicking on a different marker which then scrolls to the related content bit. 

## New specification [(i)](## "A clear and unambiguous extended specification of the new or updated functionality. References to external documents should be temporary and replaced with contents before the ticket is taken up by a developer.")

- Option to add one or more StoryBooks to a Map in MODx
	- Each StoryBook is presented as a layer in the StoryMap
	- StoryBook can contain one or more Chapters
	- Chapter consists of:
		- Title
		- Description (i.e. content that can be built through contentBlocks)
		- Location (address or geolocation)
		- Marker icon (with default)
		- Map zoom level
		- Order
		- StoryBook parent

## New design [(i)](## "A clear and unambiguous extended design of the new functionality. References to external documents should be temporary and replaced with contents before the ticket is taken up by a developer.")
...

## Existing specification [(i)](## "Link(s) to the specification regarding the relevant existing functionality. The links or surrounding text should clearly indicate what is being referenced, so the information can also be found if the link goes 404.")
- ...

## Existing design [(i)](## "If the issue concerns visual matters at all, link(s) to the designs regarding the relevant existing functionality. The links or surrounding text should clearly indicate what is being referenced, so the information can also be found if the link goes 404.")
- ...

## Additional information
...

**Comment by hugopeek** [comment]
Still work-in-progress, but first prototype included in v0.2.0 release.

@martenwilmink You mentioned:

> Option to add one or more StoryBooks to a Map in MODx
> Each StoryBook is presented as a layer in the StoryMap

I don't know how you envisioned having multiple layers in the StoryMap, but for now that would make things needlessly complicated I feel. So I flattened the StoryBook and StoryMap parts into just the StoryMap. This is a resource, containing a single story with multiple chapters. 

The chapters can be added, sorted and edited with ContentBlocks as suggested. Each chapter is connected to a Place, which contains the actual geo coordinates. It's better and easier to fetch these from a database table directly, as opposed to fidgetting them in with ContentBlocks (which is more geared towards presentation).

Places can be added via a MIGX grid, accessible from the top menu. I'm still figuring out the best way to connect a Place to a StoryMap chapter, so please consider the current approach experimental :)

**Comment by martenwilmink** [comment]
@hugopeek I think the current setup works great for now. As mentioned, I don't think we need the MIGX stories in the top menu as a separate menu item/tab, but just manage Places there.

> Places can be added via a MIGX grid, accessible from the top menu. I'm still figuring out the best way to connect a Place to a StoryMap chapter, so please consider the current approach experimental :)

See #12 

Otherwise works great! I'm closing this issue, since the Pilot MVP works.
