### ISSUE TITLE
Geometry of type lineString from GeoJSON data not showing on Map layer

### ISSUE THREAD

**Issue by martenwilmink** [martenwilmink/reframe-brain#7]
## Issue description [(i)](## "A (short) description as to what the issue is.")

We've received the geo data for the proposed SGPC road that I have converted to GeoJSON format. After adding a chunk in MODx with the data and adding a layer in the map the line is not shown however.

## Reproduction instructions [(i)](## "Step by step reproduction instructions for the bug or a clear indication of where what went wrong exactly if it cannot be reproduced.")

- Login to [dev.reframeproject.com/manager/](https://dev.reframeproject.com/manager/) as admin
- Navigate to Elements > Chunks > Project > [geoJSON_sgpc](https://dev.reframeproject.com/manager/?a=element/chunk/update&id=100098)
- Notice GeoJSON data (in correct format?)
- Navigate to Resources > Development (context) > [Map](https://dev.reframeproject.com/manager/?a=resource/update&id=47)
- Ensure Layer `SlaveGeologicalProvinceCorridor` has been added with reference to chunk `[[$geoJSON_sgpc]]`
- Click Save
- Click View
- Enable layer `SlaveGeologicalProvinceCorridor` on Map
- Notice the line for the proposed road is not showing up

## Related exceptions, screenshots, etc. [(i)](## "(Links to) exceptions, including the actual exception text or descriptions of the errors as _specific_ as possible and if relevant screenshots or videos of the issue. In general anything that is 'proof' of the issue.")
- N/A

## Acceptance criteria / TODO [(i)](## "The (key) elements that when completed / fulfilled complete this issue.")
- Ensure geometry of type lineString from GeoJSON data is rendered correctly

## Additional information
- [SGPC_road-geojson.zip](https://github.com/user-attachments/files/17104832/SGPC_road-geojson.zip)
- [SGPC_road-shapefile.zip](https://github.com/user-attachments/files/17104833/SGPC_road-shapefile.zip)

## TODO
- [x] Self review of issue specification
- [x] Lead dev review of issue specification

----
/label ~"Workflow::1-Specification"

**Comment by hugopeek** [comment]
Hi Marten, the JSON is correct, but the coordinates don't make sense.. They should be in the range between 0-180. Something like: `[ -116.43,63.6144 ]`

I'll check out the original shapefile to see what's in there. How did you convert it?

**Comment by hugopeek** [comment]
I was able to convert the shapefile with Qgis, but there's a new problem:

The generated GeoJSON file is over 20MB, and loading it leads to all kinds of caching / out-of-memory issues. It's too hot to handle for both MODX and PHP.

I'll try allocating more memory first, but even if it works, that would be a band-aid solution..

**Comment by hugopeek** [comment]
I increased the memory limit to 512MB. It works... Until someday, it doesn't ;)

I also created a static resource, pointing to a JSON file inside the _project folder. The data is too big to fit inside a chunk. And if it's static, MODX will not complain too much and just serve the raw file.

~~It works for me on localhost; I can see the roads.. But somehow on dev, it has a problem loading Leaflet.~~

Scratch that, my bad. It works now, but it's very slow to load... (for me, anyway)

**Comment by martenwilmink** [comment]
@hugopeek I don't think that the GeoJSON should be 20MB, that seems very very large for a single lineString. Let me try and convert it again with the knowledge that the coordinates were incorrect. Happy to know that this should work otherwise.

**Comment by martenwilmink** [comment]
@hugopeek Great success! I've converted the file in QGIS with a different CRS (Coordinate Reference System), namely 4326 - apparently that is the LAT/LONG coordinates as opposed to the X/Y coordinates from the original shapefile. The resulting export for the GeoJSON file is only 11 KB, so I think we're good. Check the results: [https://dev.reframeproject.com/map/](https://dev.reframeproject.com/map/)

I'm still really curious how you managed to get a 20MB file from that small route.

In the near future I will chop the route up in pieces and play around with it some more to create the 3 segments as shown in the map. Closing this issue for now.

**Comment by hugopeek** [comment]
@martenwilmink Nice work! I thought it just had a looooot of coordinates along the route. A very high resolution, so to say.

Ah, and I see now that my extract didn't just contain the proposed road, but a whole network of roads all throughout the region. Perhaps I selected the wrong file? :sweat_smile:
